import type { ImageScene } from '../../../types';
import { s, BG } from '../../styles';

export const scene: ImageScene = {
  type: 'image-text',
  duration: 9,
  backgroundColor: BG,
  transition: 'cut',
  overlays: [
    { text: '48,417 tonnes CO2e. In total.',                                                                       x: 0.1, y: 0.12, ...s.headlineLg },
    { text: 'The equivalent of the annual carbon footprint of 17,932 UK homes.',                                   x: 0.1, y: 0.30, ...s.bodyMuted, maxWidth: 0.65 },
    { text: 'Embodied in unnecessary timber. Unnecessary nails. Unnecessary plaster. Unnecessary lorry journeys.', x: 0.1, y: 0.52, ...s.subtle,   maxWidth: 0.65 },
    { text: 'Generated by a button that took Jane 2.47 seconds to press.',                                         x: 0.1, y: 0.75, ...s.accent,   maxWidth: 0.65 },
  ],
};
