import { ReferencesSlide as SharedReferencesSlide, Ref } from '@/components/slides/ReferencesSlide';

const refs: Ref[] = [
  {
    num: 1,
    publisher: 'Precedence Research',
    title: 'Precast Concrete Market Size, Share & Forecast to 2035',
    url: 'precedenceresearch.com/precast-concrete-market',
    href: 'https://www.precedenceresearch.com/precast-concrete-market',
    supports: 'Precast market value $160.5B–$175.1B (2025); ~1,435 US businesses',
  },
  {
    num: 2,
    publisher: 'Grand View Research',
    title: 'Volumetric Construction Market Size, Share & Growth Report 2030',
    url: 'grandviewresearch.com/industry-analysis/volumetric-construction-market-report',
    href: 'https://www.grandviewresearch.com/industry-analysis/volumetric-construction-market-report',
    supports: 'Volumetric market $36.03B (2025); 600–800 global companies',
  },
  {
    num: 3,
    publisher: 'MarketsandMarkets',
    title: 'Permanent Modular Construction Market worth $111.75 billion by 2030',
    url: 'marketsandmarkets.com/Market-Reports/permanent-modular-construction-market',
    href: 'https://www.marketsandmarkets.com/Market-Reports/permanent-modular-construction-market-176227460.html',
    supports: 'Permanent modular 63.8% revenue share; residential 54% of end-use',
  },
  {
    num: 4,
    publisher: 'Kentley Insights',
    title: 'Roof & Floor Truss Manufacturing Market Report 2025',
    url: 'kentleyinsights.com/industries/roof-floor-truss-manufacturing',
    href: 'https://www.kentleyinsights.com/industries/roof-floor-truss-manufacturing',
    supports: '608 US truss manufacturers; ~35,000 workers; timber trusses 58–60% of market',
  },
  {
    num: 5,
    publisher: 'Future Market Insights / Research Nester',
    title: 'Timber Frame, CLT & LGS Construction Markets 2025–2035',
    url: 'futuremarketinsights.com/reports/timber-construction-market',
    href: 'https://www.futuremarketinsights.com/reports/timber-construction-market',
    supports: 'Timber frame $39.2B–$48B; LGS $31.7B–$40.4B; CLT ecosystem $32B (2025)',
  },
  {
    num: 6,
    publisher: 'FMI Corporation',
    title: '2024 Labor Productivity Study Part 2: Prefabrication',
    url: 'fmicorp.com/insights/thought-leadership/2024-labor-productivity-study-part-2-prefabrication',
    href: 'https://fmicorp.com/insights/thought-leadership/2024-labor-productivity-study-part-2-prefabrication',
    supports: '$30–40B lost profits from labor inefficiency; 78% schedule savings; 16%→34% prefab labor hours',
  },
  {
    num: 7,
    publisher: 'PipeCloud',
    title: 'What is the ROI of implementing an MES in pipe prefabrication?',
    url: 'pipecloud.fi/what-is-the-roi-of-implementing-an-mes-in-pipe-prefabrication',
    href: 'https://pipecloud.fi/what-is-the-roi-of-implementing-an-mes-in-pipe-prefabrication/',
    supports: 'MES ROI positive within 12–18 months; 10–15% waste reduction',
  },
  {
    num: 8,
    publisher: 'Autodesk Construction Cloud',
    title: '100+ Construction Industry Statistics',
    url: 'autodesk.com/blogs/construction/construction-industry-statistics',
    href: 'https://www.autodesk.com/blogs/construction/construction-industry-statistics/',
    supports: '13 hrs/week searching for data; 52% rework from miscommunication; 14% rework from bad data',
  },
  {
    num: 9,
    publisher: 'Trimble Viewpoint (citing McKinsey)',
    title: 'The Cost of Doing Nothing: 5 Reasons Contractors Need to Modernize',
    url: 'trimble.com/viewpoint: The Cost of Doing Nothing (PDF)',
    href: 'https://assets.ctfassets.net/jnzexz4x7lkk/WtA48SOV13UPNguoR1KeO/7804b85ff9c5fba6e07186edbbd133be/the-cost-of-doing-nothing-5-reasons-contractors-need-to-modernize-their-operations-to-stay-competitive-and-profitable.pdf',
    supports: 'Digital transformation: 14–15% productivity increase; 4–6% cost reduction (McKinsey)',
  },
  {
    num: 10,
    publisher: 'KPMG (via GoCodes)',
    title: '2023 Global Construction Survey',
    url: 'gocodes.com/construction/project-management-statistics',
    href: 'https://gocodes.com/construction/project-management-statistics/',
    supports: '83% of firms say improving estimating accuracy is their biggest priority',
  },
  {
    num: 11,
    publisher: 'SketchDeck',
    title: 'The Ultimate Guide to Steel Estimating: Best Practices for Fabrication Success',
    url: 'sketchdeck.ai/blog/the-ultimate-guide-to-steel-estimating',
    href: 'https://sketchdeck.ai/blog/the-ultimate-guide-to-steel-estimating-best-practices-for-fabrication-success/',
    supports: 'AI-powered takeoff: 50–80% reduction in takeoff time; 2–3x more bids with same headcount',
  },
  {
    num: 12,
    publisher: 'Dodge Data & Analytics',
    title: 'Major Growth Expected for Prefabrication and Modular Construction',
    url: 'construction.com/reports/major-growth-expected-for-prefab-and-modular-construction',
    href: 'https://www.construction.com/reports/major-growth-expected-for-prefab-and-modular-construction/',
    supports: '90% of prefab users report improved productivity, quality, and schedule certainty',
  },
  {
    num: 14,
    publisher: 'FMI Corp / Autodesk',
    title: 'Big Data and Digital Transformation in Construction',
    url: 'fmicorp.com/uploads/media/FMI_BigDataReport.pdf',
    href: 'https://fmicorp.com/uploads/media/FMI_BigDataReport.pdf',
    supports: '49% of firms forced to transfer data manually between applications; 35% of professional time lost to non-optimal activities',
  },
  {
    num: 15,
    publisher: 'Numeric / APQC',
    title: 'How Long Does Month-End Close Take? Benchmarks & Analysis',
    url: 'numeric.io/blog/how-long-does-month-end-close-take',
    href: 'https://www.numeric.io/blog/how-long-does-month-end-close-take',
    supports: 'Top performers close in 4.8 days; mid-sized non-automated firms average 14 days',
  },
  {
    num: 16,
    publisher: 'Lean Construction Institute (citing CII)',
    title: 'Lean Construction / Integrated Project Delivery',
    url: 'leanipd.com/lean-construction',
    href: 'https://leanipd.com/lean-construction/',
    supports: 'Over 50% of labor time in construction is waste; only 43% productive vs 88% in manufacturing (CII benchmark)',
  },
  {
    num: 17,
    publisher: 'Dodge Data & Analytics / Procore',
    title: 'Top Business Issues for Specialty Contractors (2022)',
    url: 'mkt-cdn.procore.com/downloads/reports/top-business-issues-SCs.pdf',
    href: 'https://mkt-cdn.procore.com/downloads/reports/top-business-issues-SCs.pdf',
    supports: '99% of specialty contractors experience margin erosion; average 5% fade; 29% cite inaccurate estimates as primary cause',
  },
  {
    num: 13,
    publisher: 'McKinsey Global Institute',
    title: 'Digital America: A Tale of the Haves and Have-Mores (MGI Industry Digitization Index)',
    url: 'mckinsey.com/mgi/overview/in-the-news/which-industries-are-the-most-digital',
    href: 'https://www.mckinsey.com/mgi/overview/in-the-news/which-industries-are-the-most-digital',
    supports: 'Construction ranks 2nd lowest of all industries on the MGI Industry Digitization Index, ahead only of agriculture',
  },
];

export function ReferencesSlide() {
  return <SharedReferencesSlide refs={refs} />;
}
